### ISSUE TITLE
Prismatic Schema out of date

### ISSUE THREAD

**Issue by ghostandthemachine** [LockedOn/graph-router#1]
Currently graph-router is using 0.4.4 of schema and the current version is 1.0.4. When trying to use graph-router in projects with other libraries using schema graph-router is broken with StackOverFlow errors from schema.

This can be reproduced by bumping the version to the latest schema version and trying to run the tests.

**Comment by karlmikko** [comment]
Thanks @ghostandthemachine I can reproduce the issue!

**Comment by ghostandthemachine** [comment]
Awesome. I'm excited to start experimenting once it's patched. Thanks for the response

**Comment by karlmikko** [comment]
prismatic/schema now updated to 1.0.4
